Add Ruff linting support
lincc-frameworks/python-project-template pull request #355
Opened 2024-01-29 23:22 UTC by smcguire-cmu

## Change Description

Adds the option to use the Ruff linter. If selected, adds the appropriate pre-commit hook, GitHub Action check, and config to the pyproject.toml

I'm a bit unsure about what rules to use here. There are [lots of rules Ruff has](https://docs.astral.sh/ruff/rules/) that are split up into groups you can select to apply in the config. I found the default option (specifying nothing in the config) to be pretty weak (doesn't even catch a line length too long). They give on their site an [example configuration](https://docs.astral.sh/ruff/linter/#rule-selection) with popular rules, and I've added that as the default config in pyproject.toml, but this is still a lot weaker than the pylint config we use in our projects. (Doesn't check docstrings or variable names, or whitespace). If we switch to using it in our projects, which I think I'd like to try, It will definitely need some more configuring of the rules, but I don't know how much we want to set that as a default for the template.

## Checklist

- [x] This PR is meant for the `lincc-frameworks/python-project-template` repo and not a downstream one instead.
- [x] This change is linked to an open issue
- [ ] This change includes integration testing, or is small enough to be covered by existing tests

2024-01-29 23:54 UTC, drewoldag commented on python-project-template/.pre-commit-config.yaml.jinja
Do you have relatively high confidence that the `ruff` that's run here will use the same config flags as the `ruff` that is run in CI?

2024-01-30 00:00 UTC, drewoldag commented
We should also update the documentation in a couple of places, namely:
https://lincc-ppt.readthedocs.io/en/latest/source/new_project.html
and 
https://lincc-ppt.readthedocs.io/en/latest/practices/linting.html

Otherwise this looks great!

To your point about the config options, it looks like Rubin DM has a section of their style guide that lays out the ruff config that would meet their requirement. https://developer.lsst.io/python/style.html#ruff-configuration-files

I'm not sure that we should adopt that outright as the default for our template or not. It might be too much for some projects. What are your thoughts on it @smcguire-cmu?

2024-01-30 00:02 UTC, drewoldag requested changes
Leaving a "Request changes" response always feels so passive aggressive. I'm sorry :( 

I just wanted to make sure that the documentation is updated at the same time as the rest of this great work!

2024-01-30 00:22 UTC, smcguire-cmu commented on python-project-template/.pre-commit-config.yaml.jinja
It has in my testing of it, that the pre-commit errors mirrors my testing in the command line through changing files and configs.

2024-01-30 04:25 UTC, drewoldag commented on python-project-template/.pre-commit-config.yaml.jinja
Sounds good, thanks!

2024-01-30 21:14 UTC, drewoldag commented
I think the approach to use the mostly defaults plus the Rubin bits makes sense @smcguire-cmu. This all looks great, thanks a bunch for putting it all together!

2024-01-30 21:14 UTC, drewoldag approved these changes
Looks great, thank you!

2024-01-30 22:30 UTC, merged